### ISSUE TITLE
The Jacoco Maven Plugin causes problems with JDK 9

### ISSUE THREAD

**Issue by blalasaadri** [JosePaumard/streams-utils#10]
Trying to run `mvn test` currently causes the error

    Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
    Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
        at org.jacoco.agent.rt.internal_14f7ee5.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
        at org.jacoco.agent.rt.internal_14f7ee5.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
        at org.jacoco.agent.rt.internal_14f7ee5.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_14f7ee5.PreMain.premain(PreMain.java:47)
        ... 6 more
    Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:1956)
        at org.jacoco.agent.rt.internal_14f7ee5.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
        ... 9 more

**Comment by blalasaadri** [comment]
It works with an updated version of the plugin, so I've created a pull request for that.

**Comment by JosePaumard** [comment]
Same answer as your other comment: this version of Jacoco does not support Java 8.

**Comment by blalasaadri** [comment]
I'm guessing you mean that version 1.7 of stream-utils doesn't support Java 9; however, the new version of Jacoco _does_ support Java 8 (which I just tested).

**Comment by JosePaumard** [comment]
2.0 now supports Java 9.
